backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'feat({{collection}}): create “{{slug}}”'
    update: 'fix({{collection}}): update “{{slug}}”'
    delete: 'fix({{collection}}): delete “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

local_backend: true

media_folder: static/media
public_folder: /media

locale: 'fr'

collections:
  - name: 'journaux_communaux'
    label: 'Journaux Communaux'
    folder: 'src/content/journaux_communaux'
    media_folder: '/{{media_folder}}/files/journaux_communaux'
    public_folder: '{{public_folder}}/files/journaux_communaux'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'journal-communaux',
        }
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Fichier PDF', name: 'file', widget: 'file' }
  - name: 'deliberations'
    label: 'Délibérations'
    folder: 'src/content/deliberations'
    media_folder: '/{{media_folder}}/files/deliberations'
    public_folder: '{{public_folder}}/files/deliberations'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'deliberations',
        }
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Fichier PDF', name: 'file', widget: 'file' }
  - name: 'ecole'
    label: 'Ecole'
    folder: 'src/content/ecole'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'ecole',
        }
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Equipe enseignante', name: 'equipe', widget: 'markdown' }
      - { label: 'Effectifs', name: 'effectifs', widget: 'markdown' }
      - { label: 'Services', name: 'services', widget: 'markdown' }
      - {
          label: 'Photos',
          name: 'photos',
          widget: 'list',
          field:
            {
              label: 'photo',
              name: 'photo',
              widget: 'image',
              default: 'photo',
            },
        }
