backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

locale: 'fr'

collections:
  - name: 'journaux_communaux'
    label: 'Journaux Communaux'
    folder: 'src/content/journaux_communaux'
    media_folder: static/files/journaux_communaux
    public_folder: /files/journaux_communaux
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'journaux-communaux',
        }
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Fichier PDF',
          name: 'file',
          widget: 'file',
          media_library: { media_folder: '/static/files/journaux_communaux' },
        }
